version: 2
references:
  python_2_7_image: &python_2_7_image
    working_directory: ~/circleci
    docker:
      - image: circleci/python:2.7
  workspace_cache_key: &workspace_cache_key
    repo-{{ .Environment.CIRCLE_SHA1 }}
  restore_workspace: &restore_workspace
    restore_cache:
      name: Restore workspace cache
      key: *workspace_cache_key
  pip_cache_key: &pip_cache_key
    pip-v1-{{ checksum "setup.py" }}
  restore_pip_local_env: &restore_pip_local_env
    restore_cache:
      keys:
        - *pip_cache_key
        - pip-v1-
jobs:
  build_and_test:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: |
            virtualenv local-env
            . local-env/bin/activate
            pip install -e .[dev]
      - run:
          name: Running tests
          command: |
            . local-env/bin/activate
            tests/test.sh
      - store_test_results:
            path: tmp
      - save_cache:
          key: *pip_cache_key
          paths:
            - "local-env"
      - save_cache:
          key: *workspace_cache_key
          paths: ~/circleci
  release:
    <<: *python_2_7_image
    steps:
      - *restore_workspace
      - *restore_pip_local_env
      - run:
          name: Release
          command: |
            . local-env/bin/activate
            semantic-release publish
            python setup.py sdist bdist_wheel
workflows:
  version: 2
  build_and_release:
    jobs:
      - build_and_test:
      - release:
          requires:
            - build_and_test
          filters:
            branches:
              only:
                - master